In [16]:
import numpy as np

def initialize_weights_and_threshold(num_features):
    # Initialize weights with small random values and threshold to 0
    weights = np.random.rand(num_features + 1)  # Add 1 for the bias term
    threshold = 0
    return weights, threshold


def perceptron_train(inputs, targets, weights, threshold, learning_rate=0.1, max_iterations=1000):
    num_iterations = 0
    converged = False

    while not converged and num_iterations < max_iterations:
        num_iterations += 1
        converged = True

        for input_data, target in zip(inputs, targets):
            # Add bias term to input_data
            input_data_with_bias = np.insert(input_data, 0, 1)
            print(input_data_with_bias)
            
            # Calculate the weighted sum
            weighted_sum = np.dot(weights, input_data_with_bias)
            print(weighted_sum)

            # Apply the threshold function
            output = 1 if weighted_sum > threshold else 0

            # Update weights if necessary
            if output != target:
                converged = False
                weights += learning_rate * (target - output) * input_data_with_bias

    return weights, num_iterations

# Example usage:
# Define training data (inputs and corresponding targets)
inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
print("input: ", inputs)
targets = np.array([0, 0, 0, 1])
print("target:\n", targets)

# Initialize weights and threshold
num_features = len(inputs[0])
print("number of feature:",num_features)
weights, threshold = initialize_weights_and_threshold(num_features)

# Train the perceptron
trained_weights, num_iterations = perceptron_train(inputs, targets, weights, threshold)

# Print the results
print(f"Converged in {num_iterations} iterations")
print("Trained Weights:", trained_weights)


input:  [[0 0]
 [0 1]
 [1 0]
 [1 1]]
target:
 [0 0 0 1]
number of feature: 2
[1 0 0]
0.3796013322385713
[1 0 1]
0.4270970554608937
[1 1 0]
0.27825918532805516
[1 1 1]
0.12575490855037752
[1 0 0]
0.0796013322385713
[1 0 1]
0.027097055460893693
[1 1 0]
-0.12174081467194489
[1 1 1]
-0.1742450914496225
[1 0 0]
-0.020398667761428707
[1 0 1]
0.027097055460893693
[1 1 0]
-0.021740814671944886
[1 1 1]
-0.07424509144962249
[1 0 0]
-0.020398667761428707
[1 0 1]
0.027097055460893693
[1 1 0]
0.07825918532805512
[1 1 1]
-0.1742450914496225
[1 0 0]
-0.12039866776142871
[1 0 1]
-0.07290294453910631
[1 1 0]
0.07825918532805512
[1 1 1]
-0.07424509144962249
[1 0 0]
-0.12039866776142871
[1 0 1]
0.027097055460893693
[1 1 0]
-0.021740814671944886
[1 1 1]
0.025754908550377514
[1 0 0]
-0.22039866776142872
[1 0 1]
-0.17290294453910632
[1 1 0]
-0.021740814671944886
[1 1 1]
0.025754908550377514
Converged in 7 iterations
Trained Weights: [-0.22039867  0.19865785  0.04749572]
